# Generated by Django 4.2.4 on 2023-08-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draconido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidad', models.PositiveIntegerField(default=30)),
                ('linaje_draconico', models.CharField(blank=True, max_length=100)),
                ('ataque_de_aliento', models.CharField(blank=True, max_length=100)),
                ('resistencia_al_danio', models.CharField(blank=True, max_length=100)),
                ('idiomas', models.CharField(default='Común, Dragón', max_length=100)),
                ('fuerza_mod', models.IntegerField(default=2)),
                ('carisma_mod', models.IntegerField(default=1)),
                ('edad', models.PositiveIntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='Elfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidad', models.PositiveIntegerField(default=30)),
                ('vision_en_la_oscuridad', models.BooleanField(default=True)),
                ('linaje_feerico', models.BooleanField(default=True)),
                ('trance', models.BooleanField(default=True)),
                ('idiomas', models.CharField(default='Común, Élfico', max_length=100)),
                ('destreza_mod', models.IntegerField(default=2)),
                ('edad', models.PositiveIntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='Enano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidad', models.PositiveIntegerField(default=25)),
                ('vision_en_la_oscuridad', models.BooleanField(default=True)),
                ('fortaleza_enana', models.BooleanField(default=True)),
                ('afinidad_con_la_piedra', models.BooleanField(default=True)),
                ('idiomas', models.CharField(default='Común, Enano', max_length=100)),
                ('constitucion_mod', models.IntegerField(default=2)),
                ('herramientas_de_artesano', models.CharField(blank=True, max_length=100)),
                ('edad', models.PositiveIntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='Gnomo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidad', models.PositiveIntegerField(default=25)),
                ('vision_en_la_oscuridad', models.BooleanField(default=True)),
                ('astucia_de_gnomo', models.BooleanField(default=True)),
                ('idiomas', models.CharField(default='Común, Gnomo', max_length=100)),
                ('inteligencia_mod', models.IntegerField(default=2)),
                ('edad', models.PositiveIntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='Humano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidad', models.PositiveIntegerField(default=30)),
                ('alineamiento', models.CharField(default='Varía ampliamente', max_length=100)),
                ('idiomas', models.CharField(default='Común y un idioma adicional de elección', max_length=100)),
                ('fuerza_mod', models.IntegerField(default=1)),
                ('destreza_mod', models.IntegerField(default=1)),
                ('constitucion_mod', models.IntegerField(default=1)),
                ('inteligencia_mod', models.IntegerField(default=1)),
                ('sabiduria_mod', models.IntegerField(default=1)),
                ('carisma_mod', models.IntegerField(default=1)),
                ('edad', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mediano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidad', models.PositiveIntegerField(default=25)),
                ('idiomas', models.CharField(default='Común, Mediano', max_length=100)),
                ('agilidad_de_los_medianos', models.BooleanField(default=True)),
                ('valiente', models.BooleanField(default=True)),
                ('afortunado', models.BooleanField(default=True)),
                ('destreza_mod', models.IntegerField(default=2)),
                ('edad', models.PositiveIntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='Semielfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidad', models.PositiveIntegerField(default=30)),
                ('vision_en_la_oscuridad', models.BooleanField(default=True)),
                ('ancestro_feerico', models.BooleanField(default=True)),
                ('idiomas', models.CharField(default='Común, Élfico y un idioma adicional de elección', max_length=100)),
                ('carisma_mod', models.IntegerField(default=2)),
                ('mod_a_eleccion', models.IntegerField(default=1)),
                ('edad', models.PositiveIntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='Semiorco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidad', models.PositiveIntegerField(default=30)),
                ('vision_en_la_oscuridad', models.BooleanField(default=True)),
                ('aguante_incansable', models.BooleanField(default=True)),
                ('ataques_salvajes', models.BooleanField(default=True)),
                ('idiomas', models.CharField(default='Común, Orco', max_length=100)),
                ('fuerza_mod', models.IntegerField(default=2)),
                ('constitucion_mod', models.IntegerField(default=1)),
                ('edad', models.PositiveIntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tiefling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidad', models.PositiveIntegerField(default=30)),
                ('vision_en_la_oscuridad', models.BooleanField(default=True)),
                ('legado_infernal', models.BooleanField(default=True)),
                ('resistencia_infernal', models.BooleanField(default=True)),
                ('idiomas', models.CharField(default='Común, Infernal', max_length=100)),
                ('carisma_mod', models.IntegerField(default=2)),
                ('inteligencia_mod', models.IntegerField(default=1)),
                ('edad', models.PositiveIntegerField(default=500)),
            ],
        ),
    ]
